version: '3'

services:
  #####################################################
  # Ego
  #####################################################
  ego-db:
    image: "postgres:9.6"
    environment:
      PGPORT: 5432
      POSTGRES_DB: ego
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 18888:5432
  ego-api:
    image: "overture/ego:5b1ebd8-alpine"
    depends_on:
      - ego-db
    volumes:
      - ./ego_bootstrap:/ego_boostrap
    environment:
      SERVER_PORT: 8088
      SERVER_MANAGEMENT_PORT: 8089
      SPRING_PROFILES_ACTIVE: "auth"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://ego-db:5432/ego?stringtype=unspecified"
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_LOCATIONS: "classpath:flyway/sql,classpath:db/migration,filesystem:/ego_boostrap"
      GOOGLE_CLIENT_CLIENTID: "${GOOGLE_CLIENT_CLIENTID}"
      GOOGLE_CLIENT_CLIENTSECRET: "${GOOGLE_CLIENT_CLIENTSECRET}"
    ports:
      - 8088:8088
      - 50052:50051
  ego-ui:
    image: "overture/ego-ui:release-2.0.6"
    depends_on:
      - ego-api
    environment:
      REACT_APP_API: "http://localhost:8088"
    ports:
      - 3501:80

  #####################################################
  # Program Service
  #####################################################
  program-db:
    image: "postgres:9.6"
    environment:
      PGPORT: 5432
      POSTGRES_DB: program-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 18889:5432
  program-service:
    image: "icgcargo/program-service:8043985"
    restart: always
    depends_on:
      - ego-ui
      - program-db
    environment:
      SPRING_PROFILES_ACTIVE: "auth"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://program-db:5432/program-db?stringtype=unspecified"
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_FLYWAY_ENABLED: "true"
      APP_EGO_URL: "http://ego-api:8088"
      APP_EGO_CLIENT_ID: "program"
      APP_EGO_CLIENT_SECRET: "programsecret"
      APP_MAIL_ENABLED: "false"
      APP_DCC_ADMIN_PERMISSION: "PROGRAMSERVICE.WRITE"
    ports:
      - 9082:8082
      - 50051:50051

  #####################################################
  # ARGO Platform - GraphQL API Gateway
  #####################################################
  gateway:
    image: "icgcargo/argo-gateway:73646a1"
    depends_on:
      - ego-api
      - program-service
    environment:
      EGO_APPLICATION_ID: platform
      EGO_APPLICATION_SECRET: platformsecret
      EGO_ROOT_GRPC: ego-api:50052
      PROGRAM_SERVICE_ROOT: program-service:50051
    ports:
      - 9000:9000

      